### ISSUE TITLE
Does the README email need to be updated?

### ISSUE THREAD

**Issue by alenards** [CodeReadingClubs/Resources#21]
Hi! 

I am looking at trying to start code reading clubs internally at my work. I was curious if the email mentioned in the README was up-to-date. I sent an email as a test and MimeCast seems to think that the email isn't configured for the domain anymore: 

![Screenshot 2023-12-06 at 9 38 58 AM](https://github.com/CodeReadingClubs/Resources/assets/78614213/1e397532-5121-4417-b346-c8624faf7491)

Is it hello@codereading.club since the new resources website is https://codereading.club/

🙇 Thanks for putting all this information together. A big thank you to Katja for Katja's appearance on [Elm Radio](https://elm-radio.com/episode/code-reading-club).

**Comment by Nikomus** [comment]
The email address should indeed be [hello@codereading.club](mailto:hello@codereading.club)! Thank you for spotting this.
